name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  cancel-previous-runs:
    name: "cancel-previous-runs"
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  install-dependencies:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn install

  linter:
    needs: [install-dependencies]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn run lint

  build:
    needs: [install-dependencies]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  release-and-deploy:
    runs-on: ubuntu-latest
    needs: [linter, build]
    permissions:
      actions: write
      pull-requests: write
      contents: write
      repository-projects: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: test-release-pleases
      - name: Download artifact
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Deploy to gh-pages
        if: ${{ steps.release.outputs.release_created }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
